spring:
  data:
    redis:
      url: ${REDIS_DATASOURCE_URL:redis://localhost:6379}
app:
  jwt:
    # Generate a 512-bit (64-byte) random key by command: openssl rand -base64 64
    secret: TwIlWN/981FuI7Y2x+JSGDm15Hj54+U2DDtlr3Ij2Ycke4qpiwI/pQMSGoRlw8Vl8+EiZPw4/aC3HqBhUDWdog==
    expiration-ms: 900000  # 15 minutes in milliseconds
  client-salt: 5unpGiaw4rR3nPritDnAQw==